### ISSUE TITLE
Foto

### ISSUE THREAD

**Issue by Zvizda322** [Zvizda322/Hohnight#1]

**Comment by Zvizda322** [comment]
Знайти крутий арт 
![image](https://user-images.githubusercontent.com/57706294/68937582-b247ad80-07ad-11ea-9f11-4b7906415f71.png)

**Comment by FranklinatoR** [comment]
Знайшов 
![image](https://user-images.githubusercontent.com/57795479/68937694-e7540000-07ad-11ea-81a6-4b60ede5faec.png)

**Comment by Zvizda322** [comment]
Ок за

**Comment by Zvizda322** [comment]
Ок завдання виконано
